# This file is used to configure the Tidewave app.
# If you change this file, you must restart Tidewave.

# port = 9832
# https_port = 9833
# https_cert_path = "/path/to/cert.pem"
# https_key_path = "/path/to/key.pem"
# allow_remote_access = false

[env]
# SOME_API_KEY = "value"
